// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkbnxvvikfucvyomkxic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprYm54dnZpa2Z1Y3Z5b21reGljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MjY5NDQsImV4cCI6MjA2ODEwMjk0NH0.GanT_Q2iH6iNv9iOTLPwSXjnQYIFI_HG1R4Wt2l_-l8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});